[package]
name = "cua-platform-macos"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cua-capture = { path = "../cua-capture" }
cua-core = { path = "../cua-core" }
image.workspace = true
sha2.workspace = true
